### This project is a continuation of my Exploratory Data Analysis (EDA) on the Superstore dataset.

#### In the EDA phase, I discovered:
- High discounts lead to losses
- Certain categories are more profitable
- Regional performance varies significantly

#### Based on these insights, I built a Machine Learning model to predict whether a transaction will be profitable or not.

#### Importing the Superstore Dataset from SQL

In [1]:
import pymysql
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

conn = pymysql.connect(
    host="127.0.0.1",
    user="root",
    password="root",
    database="superstore"
)

df = pd.read_sql("SELECT * FROM superstore", conn)

df

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,category,sub_category,product_name,sales,quantity,discount,profit,order_year,order_month,shipping_days
0,1,CA-2016-152156,2016-11-08,2016-11-11,second class,CG-12520,Claire Gute,consumer,United States,Henderson,...,furniture,bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,11,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,second class,CG-12520,Claire Gute,consumer,United States,Henderson,...,furniture,chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",498.93,3,0.00,70.82,2016,11,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,second class,DV-13045,Darrin Van Huff,corporate,United States,Los Angeles,...,office supplies,labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,6,4
3,4,US-2015-108966,2015-10-11,2015-10-18,standard class,SO-20335,Sean O'Donnell,consumer,United States,Fort Lauderdale,...,furniture,tables,Bretford CR4500 Series Slim Rectangular Table,498.93,5,0.45,-39.72,2015,10,7
4,5,US-2015-108966,2015-10-11,2015-10-18,standard class,SO-20335,Sean O'Donnell,consumer,United States,Fort Lauderdale,...,office supplies,storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,10,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9689,9990,CA-2014-110422,2014-01-21,2014-01-23,second class,TB-21400,Tom Boeckenhauer,consumer,United States,Miami,...,furniture,furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10,2014,1,2
9690,9991,CA-2017-121258,2017-02-26,2017-03-03,standard class,DB-13060,Dave Brooks,consumer,United States,Costa Mesa,...,furniture,furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.63,2017,2,5
9691,9992,CA-2017-121258,2017-02-26,2017-03-03,standard class,DB-13060,Dave Brooks,consumer,United States,Costa Mesa,...,technology,phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39,2017,2,5
9692,9993,CA-2017-121258,2017-02-26,2017-03-03,standard class,DB-13060,Dave Brooks,consumer,United States,Costa Mesa,...,office supplies,paper,"It's Hot Message Books with Stickers, 2 3/4"" x...",29.60,4,0.00,13.32,2017,2,5


#### Understanding the Dataset

In [2]:
df.shape

(9694, 24)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9694 entries, 0 to 9693
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row_id         9694 non-null   int64  
 1   order_id       9694 non-null   object 
 2   order_date     9694 non-null   object 
 3   ship_date      9694 non-null   object 
 4   ship_mode      9694 non-null   object 
 5   customer_id    9694 non-null   object 
 6   customer_name  9694 non-null   object 
 7   segment        9694 non-null   object 
 8   country        9694 non-null   object 
 9   city           9694 non-null   object 
 10  state          9694 non-null   object 
 11  postal_code    9694 non-null   object 
 12  region         9694 non-null   object 
 13  product_id     9694 non-null   object 
 14  category       9694 non-null   object 
 15  sub_category   9694 non-null   object 
 16  product_name   9694 non-null   object 
 17  sales          9694 non-null   float64
 18  quantity

In [4]:
df.describe()

,row_id,sales,quantity,discount,profit,order_year,order_month,shipping_days
count,9694.000000,9694.000000,9694.000000,9694.000000,9694.000000,9694.000000,9694.000000,9694.000000
mean,4993.926140,142.247458,3.790902,0.136919,16.262837,2015.718176,7.807097,3.953992
std,2885.273358,169.869509,2.227335,0.157019,29.631472,1.124282,3.286945,1.747719
min,1.000000,0.440000,1.000000,0.000000,-39.720000,2014.000000,1.000000,0.000000
25%,2496.250000,17.480000,2.000000,0.000000,1.740000,2015.000000,5.000000,3.000000
50%,4992.500000,55.930000,3.000000,0.200000,8.730000,2016.000000,9.000000,4.000000
75%,7489.750000,214.850000,5.000000,0.200000,30.005000,2017.000000,11.000000,5.000000
max,9994.000000,498.930000,14.000000,0.500000,70.820000,2017.000000,12.000000,7.000000


In [5]:
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
order_year       0
order_month      0
shipping_days    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,category,sub_category,product_name,sales,quantity,discount,profit,order_year,order_month,shipping_days
0,1,CA-2016-152156,2016-11-08,2016-11-11,second class,CG-12520,Claire Gute,consumer,United States,Henderson,...,furniture,bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,11,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,second class,CG-12520,Claire Gute,consumer,United States,Henderson,...,furniture,chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",498.93,3,0.00,70.82,2016,11,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,second class,DV-13045,Darrin Van Huff,corporate,United States,Los Angeles,...,office supplies,labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,6,4
3,4,US-2015-108966,2015-10-11,2015-10-18,standard class,SO-20335,Sean O'Donnell,consumer,United States,Fort Lauderdale,...,furniture,tables,Bretford CR4500 Series Slim Rectangular Table,498.93,5,0.45,-39.72,2015,10,7
4,5,US-2015-108966,2015-10-11,2015-10-18,standard class,SO-20335,Sean O'Donnell,consumer,United States,Fort Lauderdale,...,office supplies,storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,10,7


#### Adding the target column 

In [8]:
df['Target'] = df['profit'].apply(lambda x: 0 if x<0 else 1)

In [9]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit', 'order_year',
       'order_month', 'shipping_days', 'Target'],
      dtype='object')

#### Removing the unnecessary columns which will not have significance in predicting the Target 

In [10]:
df = df.drop(columns = ['row_id','order_id','order_date', 'ship_date','customer_id', 'customer_name','postal_code','product_id','order_month', 'shipping_days','order_year'],axis = 1)

In [11]:
df.columns

Index(['ship_mode', 'segment', 'country', 'city', 'state', 'region',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'Target'],
      dtype='object')

In [12]:
df["Target"].value_counts()

Target
1    7886
0    1808
Name: count, dtype: int64

#### Seperating Target column and Features 

In [13]:
x = df.drop(columns = ['profit','Target'],axis = 1)
y = df['Target']

#### Splitting data into training and testing

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

#### Converting categorical values into numerical values so that our model can understand easily.Converting these values to numerical values using One-hot encoding technique because the categorical values are nominal.

In [15]:
categorical_columns = df.select_dtypes(include = ['object'])

In [16]:
categorical_columns = categorical_columns.drop('product_name',axis = 1)

In [17]:
x_train = x_train.drop('product_name',axis = 1)
x_test = x_test.drop('product_name',axis = 1)

In [18]:
x_train[categorical_columns.columns].columns

Index(['ship_mode', 'segment', 'country', 'city', 'state', 'region',
       'category', 'sub_category'],
      dtype='object')

#### Importing OneHotEncoder from sklearn.preprocessing

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [49]:
# Fit on training categorical columns
ohe.fit(x_train[categorical_columns.columns])

X_train = x_train
X_test = x_test

# Transform
x_train_encoded = ohe.transform(x_train[categorical_columns.columns])
x_test_encoded = ohe.transform(x_test[categorical_columns.columns])

Converting Encoded columns into Dataframe

In [50]:
encoded_cols = ohe.get_feature_names_out(categorical_columns.columns)

x_train_encoded = pd.DataFrame(x_train_encoded, columns=encoded_cols, index=x_train.index)
x_test_encoded = pd.DataFrame(x_test_encoded, columns=encoded_cols, index=x_test.index)

In [51]:
X_train = X_train.drop(columns=categorical_columns.columns)
X_test = X_test.drop(columns=categorical_columns.columns)

# Concatenate
X_train = pd.concat([X_train, encoded_train_df], axis=1)
X_test = pd.concat([X_test, encoded_test_df], axis=1)

#### Using Standard Scaler for scalling the values

In [52]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train_scl = ss.fit_transform(X_train)
x_test_scl = ss.transform(X_test)

### Model Building

In [24]:
# 1st Model - SVM

In [53]:
from sklearn.svm import SVC

In [54]:
svm = SVC( kernel='rbf',class_weight='balanced')
svm.fit(x_train_scl,y_train)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,'balanced'
,verbose,False


In [55]:
svm_pred = svm.predict(x_test_scl)

In [56]:
# 2nd Model - Logistic Regression

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [59]:
lr_pred = lr.predict(X_test)

In [60]:
# 3rd Model Random Forest

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [62]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [63]:
rf_pred = rf.predict(X_test)

In [64]:
# 4rd Model - AdaBoost

In [65]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, y_train)

,estimator,None
,n_estimators,50
,learning_rate,1.0
,algorithm,'deprecated'
,random_state,None


In [66]:
ada_pred = ada.predict(X_test)

### Models Evaluation

In [67]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score

In [68]:
def evaluate_model(y_pred,y_test,model_name):
    print("Model:",model_name)
    acc = accuracy_score(y_pred,y_test)
    prec = precision_score(y_pred,y_test)
    rec = recall_score(y_pred,y_test)
    f1 = f1_score(y_pred,y_test)
    print("Accuracy Score:",acc*100,"%")
    print("Precision Score:",prec*100,"%")
    print("Recall Score:",rec*100,"%")
    print("F1 Score:",f1*100,"%")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_pred,y_test))
    print("\n----------------------------------------------------------\n")

In [69]:
evaluate_model(svm_pred,y_test,"SVM")
evaluate_model(lr_pred,y_test,"Logistic Regression")
evaluate_model(rf_pred,y_test,"Random Forest")
evaluate_model(ada_pred,y_test,"Ada Boost")


Model: SVM
Accuracy Score: 88.91181021144921 %
Precision Score: 88.41970569417786 %
Recall Score: 97.59887005649718 %
F1 Score: 92.78281302450486 %

Confusion Matrix:
[[ 342  181]
 [  34 1382]]

----------------------------------------------------------

Model: Logistic Regression
Accuracy Score: 93.91438886023724 %
Precision Score: 98.40051183621242 %
Recall Score: 94.29797670141018 %
F1 Score: 96.3055729492799 %

Confusion Matrix:
[[ 283   25]
 [  93 1538]]

----------------------------------------------------------

Model: Random Forest
Accuracy Score: 94.48169159360495 %
Precision Score: 98.0806142034549 %
Recall Score: 95.21739130434783 %
F1 Score: 96.62779703750394 %

Confusion Matrix:
[[ 299   30]
 [  77 1533]]

----------------------------------------------------------

Model: Ada Boost
Accuracy Score: 94.27539969056214 %
Precision Score: 99.74408189379399 %
Recall Score: 93.57743097238895 %
F1 Score: 96.5624032208114 %

Confusion Matrix:
[[ 269    4]
 [ 107 1559]]

-----------

#### Comparing all models

#### Model-by-Model Insight

### Final Model Selection:

#### Business Interpretation
The Random Forest model provides the best balance between capturing important cases and minimizing costly errors, making it the most suitable choice for real-world deployment.

#### Final Conclusion Section:

After evaluating multiple models, Random Forest emerges as the best-performing model for this problem.

It achieved the highest F1 Score (96.63%) and highest Accuracy (94.48%)
Maintains an excellent balance between:
Precision (98.08%) → highly reliable predictions
Recall (95.21%) → captures most of the important cases
Produces low false positives and low false negatives, making it robust in real-world scenarios

While Logistic Regression offers strong interpretability and AdaBoost achieves near-perfect precision, Random Forest provides the most consistent and balanced performance overall.